apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGFlYTE2bDVq
  CLOUDINARY_KEY: MjQxNjcxMzEyNTM2NDQy
  CLOUDINARY_SECRET: cmFFaGRLUkRzWUJ3OU8zQ1lLUGRGN2liRG1J
  MAPBOX_TOKEN: cGsuZXlKMUlqb2liV0ZvWlhOb1pHVmxkR2tpTENKaElqb2lZMjF0Y0hveE5HNHlNR2hrTVRKeGMySXdjbmRoYnpnemVTSjkubmJXeTdmblhkSThIb3FWbVo1cW5IQQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjExMjJAY2x1c3RlcjAuZW1sdGpjbS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
